Tasks/task1
alexandr-irza/altexsoft-lab-2020 pull request #1
Opened 2020-07-30 09:29 UTC by alexandr-irza

Alpha version

2020-07-31 07:45 UTC, alex-geraschenko requested changes
Попробуйте разнести задачи по разным классам, чтобы соответствовать принципам SOLID

2020-07-31 07:45 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +    static class CmdCommands
Классы лучше выносить в отдельные файлы.

2020-07-31 07:45 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +        static string ReverseString(string input)
Посмотрите на стандартные методы работы со строками

2020-07-31 07:45 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +                if (Path.GetDirectoryName(path) == null)
Постарайтесь уйти от дублирования кода

2020-07-31 07:45 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +                var wordDelimiters = new string[] { " ", ",", ".", ":", "\r\n", Environment.NewLine, "?", "!", "(", ")", "\"" };
Попробуйте использовать **регулярные выражения**

2020-07-31 07:45 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +                    res += (res.Length != 0 ? ", " : "") + words[i];
Обратите внимание на `string.Join`

2020-07-31 07:58 UTC, alexandr-irza commented on ConsoleApp/Program.cs
> +        static string ReverseString(string input)
Вы намекаете на использование LINQ?

2020-07-31 10:56 UTC, alexandr-irza commented on ConsoleApp/Program.cs
> +                var wordDelimiters = new string[] { " ", ",", ".", ":", "\r\n", Environment.NewLine, "?", "!", "(", ")", "\"" };
Да, с регулярными выражениями проще

2020-08-03 10:41 UTC, alex-geraschenko requested changes
В целом хорошо!
Пожалуйста, поправьте оставшиеся комментарии

2020-08-03 10:41 UTC, alex-geraschenko commented on ConsoleApp/Commands/CountWordsCommand.cs
> +            if (Path.GetDirectoryName(Location) == null)
Пожалуйста, постарайтесь уйти от дублирования кода

2020-08-03 10:41 UTC, alex-geraschenko commented on ConsoleApp/Commands/CommonCommand.cs
> +    public class CommonCommand
Этот класс лучше сделать абстрактным

2020-08-03 10:41 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +            if (command.Equals(CmdCommands.ReplaceText))
Этот набор `if` можно заменить на `switch`

2020-08-03 17:13 UTC, alex-geraschenko approved these changes

2020-08-03 18:52 UTC, merged