Tasks/task2
alexandr-irza/altexsoft-lab-2020 pull request #2
Opened 2020-08-09 20:19 UTC by alexandr-irza

Finished 2nd task

2020-08-13 16:24 UTC, alex-geraschenko requested changes

2020-08-13 16:24 UTC, alex-geraschenko commented on RecipeBook/Controllers/CategoryController.cs
> +            if (Data.Categories.ToList().Find(x => string.Equals(x.Name, category.Name, StringComparison.OrdinalIgnoreCase) && x.ParentId == category.ParentId) != null)
Такие длинные выражения трудно читаемы. Стоит вынести поиск категории в отдельную локальную переменную. И почему не использовать `SingleOrDefault` вместо `ToList.Find`?

2020-08-13 16:24 UTC, alex-geraschenko commented on RecipeBook/Controllers/CategoryController.cs
> +            var item = Data.Categories.ToList().Find(x => x.Id == categoryId);
И почему не использовать `SingleOrDefault` вместо `ToList.Find`?

2020-08-13 16:24 UTC, alex-geraschenko commented on RecipeBook/Controllers/NavigationController.cs
> +        private int TreeIndex;
Приватные поля принято называть в `camelCase`, а лучше еще добавлять `_` в начале

2020-08-13 16:24 UTC, alex-geraschenko commented on RecipeBook/Controllers/RecipeController.cs
> +            var item = Data.Recipes.ToList().Find(x => string.Equals(x.Name, recipe.Name, StringComparison.OrdinalIgnoreCase));
И почему не использовать `SingleOrDefault` вместо `ToList.Find`?

2020-08-13 16:24 UTC, alex-geraschenko commented on RecipeBook/Controllers/RecipeController.cs
> +            var item = Data.Recipes.ToList().Find(x => x.Id == recipeId);
И почему не использовать `SingleOrDefault` вместо `ToList.Find`?

2020-08-13 16:24 UTC, alex-geraschenko commented on RecipeBook/Data/DataContext.cs
> +    public class DataContext
Этот класс нарушает принципы SOLID. Обратите внимание на шаблоны `Repository/UnitOfWork`

2020-08-13 16:24 UTC, alex-geraschenko commented on RecipeBook/Data/DataProcessor.cs
> +    public class DataProcessor
Если все методы класса статические, то и сам класс тоже можно сделать статическим

2020-08-13 16:24 UTC, alex-geraschenko commented on RecipeBook/Models/BaseModel.cs
> +    public class BaseModel
Базовые классы лучше делать абстрактными

2020-08-13 16:24 UTC, alex-geraschenko commented on RecipeBook/Controllers/CommonController.cs
> +    public class CommonController
Базовые классы лучше делать абстрактными

2020-08-13 16:24 UTC, alex-geraschenko commented on RecipeBook/Models/RecipeIngredient.cs
> +        public string Id { get; set; }
Если это связь `много-ко-многим`, то отдельный ключ `Id` не нужен

2020-08-13 16:24 UTC, alex-geraschenko commented on RecipeBook/Program.cs
> +
Пожалуйста, добавьте возможность ввода юникода в командной строке, при этом чтобы файлы с сериализоваными объектами можно было читать в обычном блокноте

2020-08-18 15:57 UTC, alex-geraschenko requested changes

2020-08-18 15:57 UTC, alex-geraschenko commented on RecipeBook/Data/IUnitOfWork.cs
> +        public IRecipeRepository Recipes { get; }
По-умолчанию все методы и свойства интерфейса публичны и не должны иметь `public` модификатор, а вот для самого интерфейса стоит его добавить

2020-08-18 15:57 UTC, alex-geraschenko commented on RecipeBook/Controllers/CommonController.cs
> +        public UnitOfWork UnitOfWork { get; }
В абстрактном классе свойства, методы, конструкторы, которые используются только в классах-наследниках, лучше делать `protected`

2020-08-18 15:57 UTC, alex-geraschenko commented on RecipeBook/Data/JsonFileContext.cs
> +        IEnumerable<T> IDataContext.LoadFromFile<T>(string fileName)
Этот метод должен быть публичным

2020-08-18 15:57 UTC, alex-geraschenko commented on RecipeBook/Data/JsonFileContext.cs
> +            if (File.Exists(fileName))
Попробуйте тренарный оператор

2020-08-18 15:57 UTC, alex-geraschenko commented on RecipeBook/Program.cs
> +                    OutputLine($"Incrrect format {name}", ConsoleColor.Red);
Опечатка в тексте

2020-08-18 15:57 UTC, alex-geraschenko commented on RecipeBook/Repositories/Repository.cs
> +        public Repository(IDataContext context)
Конструктор лучше сделать `protected`

2020-08-18 15:57 UTC, alex-geraschenko commented on RecipeBook/Repositories/Repository.cs
> +        private List<T> Items { get; set; }
Зачем здесь приватное свойство?

2020-08-18 16:04 UTC, alexandr-irza commented on RecipeBook/Data/IUnitOfWork.cs
> +        public IRecipeRepository Recipes { get; }
Переноси с класса, поэтому и осталось :)

2020-08-18 16:20 UTC, alexandr-irza commented on RecipeBook/Repositories/Repository.cs
> +        private List<T> Items { get; set; }
Оно внизу используется в методе Save (перенес его повыше)

2020-08-18 16:34 UTC, alexandr-irza commented on RecipeBook/Repositories/Repository.cs
> +        private List<T> Items { get; set; }
Убрал private они и так по умолчанию приватные

2020-08-18 16:48 UTC, alex-geraschenko commented on RecipeBook/Repositories/Repository.cs
> +        private List<T> Items { get; set; }
Вопрос скорее был не в модификаторе доступа, а в том, зачем тут свойство, почему не обойтись приватным полем ?

2020-08-18 16:53 UTC, alexandr-irza commented on RecipeBook/Repositories/Repository.cs
> +        private List<T> Items { get; set; }
Не могу объяснить, на момент разработки казалось свойство будет лучше. Переделал

2020-08-19 08:00 UTC, alex-geraschenko approved these changes
Все выглядит хорошо. Можно мержить.

2020-08-19 08:24 UTC, merged