Tasks/task3
alexandr-irza/altexsoft-lab-2020 pull request #3
Opened 2020-09-10 19:01 UTC by alexandr-irza

First version of task 3

2020-09-14 15:48 UTC, alex-geraschenko requested changes

2020-09-14 15:48 UTC, alex-geraschenko commented on task3/data/1_Categories.sql
> +﻿DELETE Categories WHERE ParentId IS NOT NULL; --Remove sub categories
Дополнительный `DELETE` не нужен

2020-09-14 15:48 UTC, alex-geraschenko commented on task3/data/1_Categories.sql
> +DELETE Categories; --Remove root categories
Если этот скрипт запустить когда вся база заполнена, то будет ошибка. Лучше добавить еще один скрипт в самом начале, который будет в нужном порядке очищать таблицы, а потом отдельными скриптами заполнять таблицы

2020-09-14 15:48 UTC, alex-geraschenko commented on task3/data/4_RecipeIngredients.sql
> +﻿DELETE RecipeIngredients; --Remove exist data
Когда нет внешних ключей, можно использовать `TRUNCATE TABLE`

2020-09-14 15:48 UTC, alex-geraschenko commented on task3/data/5_RecipeSteps.sql
> +﻿DELETE RecipeSteps; --Remove exist recipes
Когда нет внешних ключей, можно использовать `TRUNCATE TABLE`

2020-09-14 15:48 UTC, alex-geraschenko commented on task3/queries/FirstThreeRecipes.sql
> +	where c.Id = 3 or c.ParentId = 3
Этот запрос не сработает, если будет больше 1-го уровня вложености категорий. Посмотрите в сторону **Common Table Expressions**

2020-09-14 17:12 UTC, alexandr-irza commented on task3/queries/FirstThreeRecipes.sql
> +	where c.Id = 3 or c.ParentId = 3
Читал об этом, но не учел что может быть больше 2 уровней.

2020-09-14 17:13 UTC, alexandr-irza commented on task3/data/1_Categories.sql
> +DELETE Categories; --Remove root categories
При заполнении данных было проще иметь удаление в каждом файле. Вынес удаление в отдельный файл.

2020-09-17 10:43 UTC, alex-geraschenko requested changes

2020-09-17 10:43 UTC, alex-geraschenko commented on task3/queries/FirstThreeRecipes.sql
> +	where c.CategoryPath like '3\%'
Лучше не стоит использовать поиск по подстроке на вычисляемых полях. Это может сказаться на производительности при больших объемах данных. Постарайтесь найти решение с использованием индексированых полей (в частности `Id`)

2020-09-17 14:16 UTC, alex-geraschenko requested changes

2020-09-17 14:16 UTC, alex-geraschenko commented on task3/queries/FirstThreeRecipes.sql
> +	where cc.CategoryId = @CategoryId or cc.CategoryParentId = @CategoryId
Условие `where` избыточно

2020-09-17 14:27 UTC, alexandr-irza commented on task3/queries/FirstThreeRecipes.sql
> +	where cc.CategoryId = @CategoryId or cc.CategoryParentId = @CategoryId
Перенес условие в джоин

2020-09-17 14:59 UTC, alex-geraschenko commented on task3/queries/FirstThreeRecipes.sql
> +	where cc.CategoryId = @CategoryId or cc.CategoryParentId = @CategoryId
Вы не так поняли, его стоит совсем убрать

2020-09-17 15:14 UTC, alex-geraschenko requested changes

2020-09-17 15:14 UTC, alex-geraschenko commented on task3/queries/FirstThreeRecipes.sql
> +	inner join Categories_CTE cc on cc.CategoryId = c.ParentId and (cc.CategoryId = @CategoryId OR cc.CategoryParentId = @CategoryId)
Условие из `WHERE` нужно было не переносить, а убрать совсем. Оно не имеет смысла, т.к. у Вас рекурсивный `CTE`

2020-09-17 15:22 UTC, alexandr-irza commented on task3/queries/FirstThreeRecipes.sql
> +	inner join Categories_CTE cc on cc.CategoryId = c.ParentId and (cc.CategoryId = @CategoryId OR cc.CategoryParentId = @CategoryId)
Уже понял, мы используем результаты предыдущего выполнения, а он уже имеет нужный фильтр

2020-09-17 15:30 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-09-17 15:33 UTC, merged