Tasks/task4
alexandr-irza/altexsoft-lab-2020 pull request #4
Opened 2020-09-20 13:44 UTC by alexandr-irza

Это задание намного сложнее. Не уверен что все пошло в правильном направлении. Жду отзывов и рекомендаций.

2020-09-22 05:37 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Infrastructure/Extensions/RecipeBookContextFactory.cs
> +            optionsBuilder.UseSqlServer("Server=localhost;Database=RecipeBook;Trusted_Connection=True;");
Одним из требований к заданию сказано, что "Строка подключения к базе данных должна браться из файла HomeTask4.Cmd/appsettings.json".

2020-09-22 05:37 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Infrastructure/Repositories/RecipeIngredientRepository.cs
> +            return null;
Возвращать null из методов достаточно неоднозначная практика. Клиентов этого кода Вы обязали проверять, не возвращает ли метод null, никак не сигнализируя, что этот код может вернуть его вернуть. А если у клиентов не будет доступа к исходному коду и они не ожидают возвращения null? 
Кроме того, поскольку это перегруженный метод, при использовании базового типа, Вам придется добавлять проверки на null везде, где Вы его используете.

2020-09-22 05:42 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Infrastructure/Extensions/RecipeBookContextFactory.cs
> +            optionsBuilder.UseSqlServer("Server=localhost;Database=RecipeBook;Trusted_Connection=True;");
Этот код нужен только для дезайнтайм для миграции. Иначе я не знаю как загрузить аппсеттингс с другого проекта.

2020-09-22 05:44 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Infrastructure/Repositories/RecipeIngredientRepository.cs
> +            return null;
Здесь моя ошибка, перенес код со 2 задания, но в этом задании немного изменилась структура и я теперь могу вернуть данные.

2020-09-22 05:47 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Infrastructure/Extensions/RecipeBookContextFactory.cs
> +            optionsBuilder.UseSqlServer("Server=localhost;Database=RecipeBook;Trusted_Connection=True;");
Насколько я понимаю, это [можно все же сделать](https://stackoverflow.com/questions/58115541/how-to-read-appsettings-from-createdbcontext). Вопрос насколько это корректно и нужно ли это. Как скажет @alex-geraschenko

2020-09-22 06:25 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Infrastructure/Extensions/RecipeBookContextFactory.cs
> +            optionsBuilder.UseSqlServer("Server=localhost;Database=RecipeBook;Trusted_Connection=True;");
Спасибо за ссылку, переделал.

2020-09-22 15:58 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Core/Entities/RecipeIngredient.cs
> +        [Key, Column(Order = 0)]
Хм, Вы уже создали composite key во время вызова OnModelCreating(). Здесь у Вас получается второй источник правды. Кроме того, документация гласит, что composite key в EF Core [можно создать только с помощью Fluent API](https://docs.microsoft.com/en-us/ef/core/modeling/keys?tabs=data-annotations).

2020-09-22 16:25 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Core/Entities/RecipeIngredient.cs
> +        [Key, Column(Order = 0)]
Я читал это, поэтому и сделал с использованием Fluent API, но забыл удалить атрибуты и компилятор не ругнулся.

2020-09-22 19:35 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.SharedKernel/Interfaces/IRepository.cs
> +    public interface IRepository<T> where T : class
В соответствии с примером, ограничением для универсального шаблона (параметра) в этом репозитории должна выступать `BaseEntity`.

2020-09-22 19:35 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Core/Interfaces/IUnitOfWork.cs
> +﻿
Лишняя пустая строка.

2020-09-22 19:35 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Infrastructure/Repositories/UnitOfWork.cs
> +            Categories = new CategoryRepository(context);
Вы уже используете встроенный в ASP.NET Core IoC контейнер, добавьте все нужные репозитории в скоуп, как Вы сделали с IUnitOfWork.

2020-09-23 20:57 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Cmd/Program.cs
> +            var rc = new RecipeController(unitOfWork);
Создание контроллеров тоже можно отдать на откуп IoC контейнеру.

2020-09-24 05:52 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Cmd/Program.cs
> +            var rc = new RecipeController(unitOfWork);
Да, но тогда Infrastructure будет зависеть от Cmd, так будет нормально?

2020-09-24 05:54 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Cmd/Program.cs
> +            var rc = new RecipeController(unitOfWork);
Или мы приходим к тому что Controllers тоже нужно перенести в Infrastructure?

2020-09-24 06:59 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Cmd/Program.cs
> +            var rc = new RecipeController(unitOfWork);
> Да, но тогда Infrastructure будет зависеть от Cmd, так будет нормально?

Конечно, Infrastructure не должен зависеть от Cmd. Вектор растространения зависимостей должен начинаться на доменном уровне и заканчиваться на уровне UI, в данном случае Cmd.

2020-09-24 07:02 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Cmd/Program.cs
> +            var rc = new RecipeController(unitOfWork);
> Или мы приходим к тому что Controllers тоже нужно перенести в Infrastructure?

Я думаю, это будет неправильно. ASP.NET Core добавляет контроллеры в IoC контейнер с помощью специального екстеншина. Возможно у Вас получиться сделать по аналогии.

2020-09-24 07:04 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Cmd/Program.cs
> +            var rc = new RecipeController(unitOfWork);
Тогда не понимаю как это можно сделать. Я должен зарегистрировать контроллеры в методе AddInfrastructure, но тогда подключится проект Cmd, а это неправильно. Что почитать чтобы понять?

2020-09-24 07:25 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Cmd/Program.cs
> +            var rc = new RecipeController(unitOfWork);
У Вас есть Infrastructure. Сущности из этого слоя Вы добавляете в IoC. Для этого Вам служит эксеншин. 
У Вас есть Cmd / Web / Whatever. Некоторые сущности Вам нужно добавить в IoC. Нужен экстеншин. Его можно положить тоже в Cmd / Web / Whatever. 
Был бы у Вас еще один слой, Вам было бы достаточно создать еще один екстеншин и вызвать его там, где Вы конфигурируете сервисы. Одним эксеншином из Infrastructure Вы все равно не обойдетесь. [Почитать можно, например, здесь](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1).

2020-09-24 07:28 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Cmd/Program.cs
> +            var rc = new RecipeController(unitOfWork);
Спасибо, почитаю. По моему начинаю понимать :)

2020-09-24 08:53 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Cmd/Program.cs
> +            var rc = new RecipeController(unitOfWork);
Подсмотрел у Александра в 5 задании. Он добавил Controllers в Core. Сделал по этой же схеме, при этом UnitOfWork сделал синглтоном.

2020-09-26 09:57 UTC, alexandr-irza commented
@serhii-shkodenko Что еще нужно пофиксить чтобы закрыть эту задачу?

2020-09-26 10:01 UTC, serhii-shkodenko commented
> @serhii-shkodenko Что еще нужно пофиксить чтобы закрыть эту задачу?

Сегодня более детально посмотрю и отвечу.

2020-09-26 15:40 UTC, serhii-shkodenko requested changes

2020-09-26 15:40 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Cmd/Program.cs
> +            var rc = host.Services.GetService <RecipeController>();
Лучше использовать `GetRequiredService()` вместо `GetService()`. Они по-разному ведут для сценария, когда запрашиваемый сервис на найден. `GetRequiredService()` выкинет исключение, `GetService()` просто вернет null.

2020-09-26 15:40 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Cmd/Program.cs
> +            nc.ReloadData();
Здесь программа упадет, если не будет найден сервис, и вы на null вызовете метод `ReloadData()`. С `GetRequiredService()`  Вы бы упали пораньше, что является более предпочтительным вариантом.

2020-09-26 15:40 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Infrastructure/Repositories/UnitOfWork.cs
> +            Categories = new CategoryRepository(context);
Вот код из примера. Сделайте, пожалуйста, аналогично. 
```
public UnitOfWork(AppDbContext context, IRepository repository)
{
        _context = context;
        Repository = repository;
}
```

2020-09-26 15:40 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Infrastructure/Repositories/UnitOfWork.cs
> +using System.Linq;
Неиспользуемый неймспейс, удалите.

2020-09-26 15:40 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Infrastructure/Data/RecipeBookContext.cs
> +            //Database.EnsureDeleted();
Закоментированный код стоит удалять перед подготовкой PR. Удалите.

2020-09-26 15:40 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Infrastructure/Repositories/CategoryRepository.cs
> +    public class CategoryRepository : BaseRepository<Category>, ICategoryRepository
В примере репозиторий находится в папке Data. Я бы всю папку с репозиториями там бы и оставил, не выносил бы отдельно.

2020-09-26 16:15 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Infrastructure/Repositories/UnitOfWork.cs
> +            Categories = new CategoryRepository(context);
Не знал что так можно, получается все будет создано автоматически, я только запрашиваю UnitOfWork, круто.

2020-09-28 15:05 UTC, alex-geraschenko requested changes

2020-09-28 15:05 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Core/Controllers/CategoryController.cs
> +                category.Parent = UnitOfWork.Categories.SingleOrDefault(x => x.Id == category.ParentId);
Тут можно заменить на `UnitOfWork.Categories.Get(category.ParentId)`

2020-09-28 15:05 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddSingleton<IUnitOfWork, UnitOfWork>();
Плохая идея делать `UnitOfWork` синглтоном. В этом случае данные из базы могут кешироваться, и приложение не будет работать корректно с актуальными данными

2020-09-28 15:05 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Infrastructure/Data/RecipeBookContext.cs
> +            modelBuilder.ApplyConfiguration(new RecipeIngredientConfig());
Не хватает конфигураций для остальных сущностей

2020-09-28 15:05 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Infrastructure/Data/BaseRepository.cs
> +        internal RecipeBookContext context;
Эти поля лучше сделать приватными

2020-09-28 15:05 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Core/Entities/Recipe.cs
> +        [MaxLength(100)]
Вместо атрибутов лучше использовать `Fluent API`

2020-09-28 15:05 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Core/Entities/Ingredient.cs
> +        [MaxLength(100)]
Вместо атрибутов лучше использовать `Fluent API`

2020-09-28 15:05 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Core/Entities/Category.cs
> +        [MaxLength(100)]
Вместо атрибутов лучше использовать `Fluent API`

2020-09-28 15:05 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Core/Controllers/CategoryController.cs
> +            var item = UnitOfWork.Categories.SingleOrDefault(x => string.Equals(x.Name, category.Name, StringComparison.OrdinalIgnoreCase) && x.ParentId == category.ParentId);
Для поиска в базе по имени достаточно будет `x => x.Name == category.Name`

2020-09-28 15:05 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Core/Controllers/RecipeController.cs
> +            var item = UnitOfWork.Recipes.SingleOrDefault(x => string.Equals(x.Name, recipe.Name, StringComparison.OrdinalIgnoreCase));
Для поиска в базе по имени достаточно будет `x => x.Name == recipe.Name`

2020-09-28 15:05 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Core/Controllers/RecipeController.cs
> +            var product = UnitOfWork.Ingredients.SingleOrDefault(x => string.Equals(x.Name, ingredientName, StringComparison.OrdinalIgnoreCase));
Для поиска в базе по имени достаточно будет `x => x.Name == ingredientName`

2020-09-29 07:41 UTC, alex-geraschenko requested changes

2020-09-29 07:41 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Infrastructure/Data/BaseRepository.cs
> +            return await _context.Set<T>().Where(predicate).ToListAsync();
В этом случае лучше обойтись без `async/await`

2020-09-29 07:41 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Infrastructure/Data/BaseRepository.cs
> +            return await _context.Set<T>().FindAsync(id);
В этом случае лучше обойтись без `async/await`

2020-09-29 07:41 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Infrastructure/Data/BaseRepository.cs
> +            return await _context.Set<T>().SingleOrDefaultAsync(predicate);
В этом случае лучше обойтись без `async/await`

2020-09-29 07:52 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Infrastructure/Data/BaseRepository.cs
> +            return await _context.Set<T>().SingleOrDefaultAsync(predicate);
Тогда для UpdateAsync тоже можно убрать?

2020-09-29 08:11 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Infrastructure/Data/BaseRepository.cs
> +            return await _context.Set<T>().SingleOrDefaultAsync(predicate);
Да, по аналогии с `RemoveAsync`

2020-09-29 11:07 UTC, alex-geraschenko approved these changes
Выглядит хорошо, можно мержить

2020-09-29 11:15 UTC, merged