Tasks/task5
alexandr-irza/altexsoft-lab-2020 pull request #5
Opened 2020-09-29 15:35 UTC by alexandr-irza

Добавил тесты

2020-09-30 19:12 UTC, serhii-shkodenko reviewed
Добавлены тесты только для контроллеров. Остуствуют тесты для репозиториев, екстеншина.

2020-09-30 19:12 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +        private List<Category> _categories;
Принято писать юнит тесты таким образом, чтобы они были изолированными друг от друга. Например, если Вы используете какой либо объект в своих тестах, для каждого из них этот объект принято создавать заново. В Вашем случае Вам приходится в каждом тесте очищать список и заполнять его новыми данными. Если Вы используете такой список в каждом тесте, метод его создания можно вынести.

2020-09-30 19:12 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +using Moq;
Обычно проекты с тестами именуют по шаблону [Project].Tests. В примере, предоставленном @alex-geraschenko, например, создан проект с тестами для Core и он называется HomeTask5.Core.Tests.

2020-09-30 19:12 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +            _repositoryMock.Setup(x => x.GetAllAsync())
Настравивать Ваши моки следует в непосредственно в тестах. Если Вы тестируете удаление, настраиваете удаление и так далее. В примере это указано. Просмотрите все тесты и поправьте, пожалуйста.

2020-09-30 19:12 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +        {
Отсутствует шаблон ААА (Arrange, Act, Assert). В примере он применяется. Просмотрите все тесты и поправьте, пожалуйста.

2020-09-30 19:12 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +        public async Task CreateCategoryAsync()
Методы принято именовать в соответствии с определенными шаблонами. С ними, например, можно ознакомиться [здесь](https://dzone.com/articles/7-popular-unit-test-naming). Вот пример имени метода от @alex-geraschenko: AddNewTempEntity_Should_Return_New_Entity. Как видите суффикс Async отсутствует. Просмотрите все тесты и поправьте, пожалуйста.

2020-09-30 19:12 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Infrastructure/Data/UnitOfWork.cs
>              Categories = categoryRepository;
А почему длдя остальных аргументов не добавили проверку на `null`?

2020-09-30 19:27 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Core/Exceptions/EmptyFieldException.cs
> +    {
Пользовательские исключения [должны имплементировать три конструктора из класса Exception](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-user-defined-exceptions).

2020-09-30 19:27 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.Core/Exceptions/EmptyFieldException.cs
> +            : base($"Field { name }.{ field } cannot be empty.")
В текущей реализации исключений я не вижу в них большого смысла. Возможно, имя поля, которое не должно быть `null`, я бы сохранил в свойство. Здесь, например, [так и поступили](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-localized-exception-messages).

2020-09-30 19:32 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +        {
Команда ASP.NET Core [тоже успешно его использует](https://github.com/dotnet/aspnetcore/blob/b795ac3546eb3e2f47a01a64feb3020794ca33bb/src/Testing/test/LogValuesAssertTest.cs#L127).

2020-09-30 19:47 UTC, alexandr-irza commented
@serhii-shkodenko спасибо, за столь детальные комментарии, это очень помогает. Тесты пишу первый раз в жизни.

2020-09-30 20:01 UTC, serhii-shkodenko commented
> @serhii-shkodenko спасибо, за столь детальные комментарии, это очень помогает. Тесты пишу первый раз в жизни.

Пожалуйста 🙂. Мне поначалу, тоже было сложно вникнуть, но потом разобрался 👨‍💻 и убедился, что тесты помагают писать более безопасный и устойчивый код 💪.

2020-10-01 09:16 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +using Moq;
В данном случае это не критично. Такой формат проектов принят в CleanArchitecture

2020-10-01 09:24 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +        private List<Category> _categories;
Да, в целом так и есть. За исключением того, что в **xUnit** для выполнения каждого теста создается новый экземпляр класса. Поэтому в данном случае нет необходимости очищать коллекцию _categories в каждом методе.

2020-10-01 11:23 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +        private List<Category> _categories;
Вот, что бывает, когда попилил тесты на NUnit, и думаешь, что в xUnit щас быстренько разберешься 🤪 (хотя всего-то нужно было читнуть первую страницу документации). Правильно ли я понимаю, что sut, зависимости к нему, другие нужные объекты (ту же коллекцию _categories, например) можно создать в конструкторе, а непосредственно в тестовых методах только вызывать somethingMock.Setup() и настраивать expectations? 

> Да, в целом так и есть. За исключением того, что в **xUnit** для выполнения каждого теста создается новый экземпляр класса. Поэтому в данном случае нет необходимости очищать коллекцию _categories в каждом методе.

2020-10-01 12:03 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +        private List<Category> _categories;
@serhii-shkodenko, да, все правильно

2020-10-01 13:58 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Core/Exceptions/EmptyFieldException.cs
> +            : base($"Field { name }.{ field } cannot be empty.")
Это нужно для тестов - Assert.Throws/ThrowsAsync, чтобы именно этот эксепшин поймать а не какойто другой

2020-10-03 10:09 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +            _repositoryMock.Setup(x => x.GetAllAsync())
А как быть с дублированием кода? например GetAll используется в каждом методе, или CreateCategory в 3 тестах.

2020-10-03 10:17 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +        {
[А здесь](https://github.com/dotnet/aspnetcore/blob/b795ac3546eb3e2f47a01a64feb3020794ca33bb/src/Testing/test/HttpClientSlimTest.cs) они не используют его и именуют методы по другому :)

2020-10-04 08:30 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Core/Exceptions/EmptyFieldException.cs
> +            : base($"Field { name }.{ field } cannot be empty.")
Переделал эксепшиныю

2020-10-04 13:56 UTC, serhii-shkodenko requested changes
По-моему,  хорошо переделали исключения. Единственное я бы добавил поля, например, NotFoundEntityName там где, это возможно. Но это на Ваше рассмотрение. 

По-прежнему отсутствуют тесты для репозиториев. @alex-geraschenko их же нужно покрывать?

2020-10-04 13:56 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +            await Assert.ThrowsAsync<NotFoundException>(async () => await controller.RemoveCategoryAsync(2));
Кроме проверки типа исключения обычно еще проверяют еще и сообщение. Добавьте пожалуйста. [Как это можно сделать](https://stackoverflow.com/questions/45017295/assert-an-exception-using-xunit).

2020-10-04 13:56 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +            _repositoryMock.Setup(x => x.Remove(It.IsAny<Category>()))
Добавьте [проверку поведения](https://habr.com/ru/post/150859/) к созданным стабам для методов.

2020-10-04 15:27 UTC, serhii-shkodenko reviewed
Некоторые замечения / размышления по поводу дублирования кода.

2020-10-04 15:27 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +            _repositoryMock.Setup(x => x.GetAllAsync())
Дело в том, что не для всех тестов Вам нужны эти сетапы. Вот что у меня получилось, когда я сократил конструктор до:

```
public CategoryControllerTests()
{
    _categories = new List<Category>();
    _unitOfWorkMock = new Mock<IUnitOfWork>();
    _controller = new CategoryController(_unitOfWorkMock.Object);
}
```
![edited_tests](https://user-images.githubusercontent.com/69808191/95018380-024e8d80-0668-11eb-9d33-cd60c1ee342b.png)
Поэтому я бы все настройки выносил бы в конкретные тесты, к тому же, как мне кажется, так будет наглядее с точки зрения написания поеденческих тестов -  все будет в одном месте.

2020-10-04 15:27 UTC, serhii-shkodenko commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +            _repositoryMock.Setup(x => x.GetAllAsync())
Вот таким у меня получился тест.
```
private List<Category> _categories;
private Mock<IUnitOfWork> _unitOfWorkMock;

private CategoryController _controller;

public CategoryControllerTests()
{
    _categories = new List<Category>();
    _unitOfWorkMock = new Mock<IUnitOfWork>();
    _controller = new CategoryController(_unitOfWorkMock.Object);
}

[Fact(DisplayName = "Create Category")]
public async Task CreateCategory_Should_Create_New_Category()
{
    // Arrange
    var categoryToAdd = new Category
    {
        Name = "Category 2",
        ParentId = null
    };

    var repositoryMock = new Mock<ICategoryRepository>();
    repositoryMock.Setup(r => r.SingleOrDefaultAsync(x => x.Name == categoryToAdd.Name && x.ParentId == categoryToAdd.ParentId)).ReturnsAsync((Category)null);
    repositoryMock.Setup(r => r.Add(categoryToAdd));

    _unitOfWorkMock.SetupGet(uow => uow.Categories).Returns(repositoryMock.Object);
    _unitOfWorkMock.Setup(uow => uow.SaveChangesAsync());

    // Act
    var result = await _controller.CreateCategoryAsync(categoryToAdd);

     // Assert
    Assert.True(result.Equals(categoryToAdd));

    repositoryMock.Verify(r => r.SingleOrDefaultAsync(x => x.Name == categoryToAdd.Name && x.ParentId == categoryToAdd.ParentId), Times.Once);
    repositoryMock.Verify(r => r.Add(categoryToAdd), Times.Once);
    _unitOfWorkMock.VerifyGet(uow => uow.Categories, Times.AtLeastOnce);
    _unitOfWorkMock.Verify(uow => uow.SaveChangesAsync(), Times.Once);
}
```
Я в целом не вижу необходимости в хранении категорий, потому что проверять физическое добавление в источник данных следует во время интеграционного тестирования или тестирования репозиториев. Для тестирования же кода, который содержится в методе `CreateCategoryAsync()` Вашего контроллера необходимости я не вижу.

2020-10-04 16:47 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.UnitTests/CategoryControllerTests.cs
> +            _repositoryMock.Setup(x => x.GetAllAsync())
Круто, у меня так не получилось, хотя тоже шел этим путем. У меня в SingleOrDefault возвращало nul и я подумал что все неправильно и пошел путем создания списка с категориями.

2020-10-05 18:43 UTC, alexandr-irza commented
Репозитории пока что не добавлял, нет ответа от Александра, нужно ли.

2020-10-05 18:58 UTC, alex-geraschenko commented
> По-прежнему отсутствуют тесты для репозиториев. @alex-geraschenko их же нужно покрывать?

На самом деле не обязательно, т.к. для тестирования репозитория необходимо будет создавать `InMemoryDatabase`, а это уже не юнит, а интеграционные тесты

2020-10-05 18:59 UTC, alex-geraschenko approved these changes
Выглядит хорошо, можно мержить

2020-10-05 19:02 UTC, serhii-shkodenko approved these changes

2020-10-05 21:18 UTC, merged