Tasks/task6
alexandr-irza/altexsoft-lab-2020 pull request #6
Opened 2020-10-18 19:10 UTC by alexandr-irza

2020-10-26 19:21 UTC, alex-geraschenko requested changes

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Index.cshtml
> +                            <label asp-for="Recipes.FirstOrDefault().Name"></label>
В данном случае использование тега `label` и `asp-for` нет смысла. Лучше использовать `@Html.DisplayNameFor(model => model.Recipes[0].Name)`

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Index.cshtml
> +                            <label asp-for="Recipes.FirstOrDefault().Description"></label>
В данном случае использование тега `label` и `asp-for` нет смысла. Лучше использовать `@Html.DisplayNameFor(model => model.Recipes[0].Description)`

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Edit.cshtml.cs
> +        public IActionResult OnPostDeleteDirectionAsync(int stepId)
У синхронного метода не должно быть суффикса `Async`

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Edit.cshtml.cs
> +        public IActionResult OnPostDeleteIngredientAsync(int ingredientId)
У синхронного метода не должно быть суффикса `Async`

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Edit.cshtml.cs
> +            ModelState.Clear();
Зачем очищать `ModelState`?

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Edit.cshtml.cs
> +            ModelState.Clear();
Зачем очищать `ModelState`?

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Edit.cshtml
> +                <a class="btn btn-info form-control text-white">Add Direction</a>
У кнопки нет действия

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Edit.cshtml
> +                <a class="btn btn-info form-control text-white">Add Ingredient</a>
У кнопки нет действия

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Edit.cshtml
> +                <textarea asp-for="Recipe.Description" Description="form-control" type="text" text-wrap="normal"></textarea>
1. Атрибут `Description` не существует.
2. Отсутствует атрибут `class`
3. Атрибут `type` для `textarea` лишний
4. Лучше добавить атрибут `rows`

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Categories/Create.cshtml.cs
> +    public class CreateModel : PageModel
Вместо `CreateModel` лучше давать более понятные имена. Например `CreateCategory`. Пожалуйста, поменяйте по всему проекту

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Categories/Create.cshtml.cs
> +            else
Если внутри `if` есть `return` то `else` не нужен. Можно сократить вложеность

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Categories/Create.cshtml
> +
Не хватает присвоения `ViewData["Title"]`. Пожалуйста, проверьте все страницы

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Edit.cshtml
> +        <input type="hidden" asp-for="Recipe.Id" />
Не хватает привязки категории

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Categories/Create.cshtml
> +@model RecipeBook2.Web.Pages.Categories.CreateModel
Лучше вынести неймспейсы `RecipeBook2.Web.Pages.*` в `Pages/_ViewImports.cshtml` как `@using`. Пожалуйста, поправьте на всех страницах

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Categories/Create.cshtml
> +                <input type="submit" value="Create" class="btn btn-primary form-control" />
Лучше везде использовать `<button type="submit">` вместо `<input type="submit">`, т.к. у первого больше возможностей. Пожалуйста, поменяйте по всему проекту

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Categories/Index.cshtml.cs
> +            ViewData["Id"] = id;
Вместо `ViewData` лучше использовать свойства

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Index.cshtml.cs
> +            _logger = logger;
`_logger` нигде не используется. Либо удалите либо используйте по назначению

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Categories/Index.cshtml
> +
Использование пустых ячеек в таблице - это плохая практика, лучше добавить атрибут `colspan="2"` для предыдущей ячейки. Пожалуйста, поправьте все страницы с такой же ситуацией

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Categories/Index.cshtml
> +                            @Html.DisplayNameFor(m => m.Categories.SingleOrDefault().Name)
Вместо `SingleOrDefault` лучше использовать `First`, т.к.:
1. Вы уже проверяете, что категории присутствуют на строчке 17, а значит значения по-умолчанию не будет
2. Категорий может быть больше чем одна

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Categories/Edit.cshtml
> +    <form method="post">
Форму  имеет смысл выделить в отдельный компонент и переиспользовать на страницах создания и редактирования. Это же касается и других сущностей

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Create.cshtml
> +        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
Не хватает привязки категории

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Create.cshtml
> +                <textarea asp-for="Recipe.Description" Description="form-control" type="text" text-wrap="normal"></textarea>
1. Атрибут `Description` не существует.
2. Отсутствует атрибут `class`
3. Атрибут `type` для `textarea` лишний
4. Лучше добавить атрибут `rows`

2020-10-26 19:21 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Categories/Index.cshtml
> +                            @Html.DisplayNameFor(m => m.Categories.SingleOrDefault().Name)
Пожалуйста, убедитесь, что Вы используете `@Html.DisplayNameFor` и на других страницах со списками

2020-11-04 05:39 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/Edit.cshtml.cs
> +            ModelState.Clear();
Почитал, ненужно.

2020-11-04 21:04 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Web/Pages/Categories/Edit.cshtml
> +    <form method="post">
Может есть ссылки по компонентам, пока что не могу конкретно ничего найти.

2020-11-05 17:08 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Categories/Edit.cshtml
> +    <form method="post">
Да, извините. Я не правильно указал. Компоненты (Razor Components) используются при создании Blazor приложений. А в случае Razor Pages или MVC это назвается `Partial View` https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-3.1

2020-11-17 20:21 UTC, alexandr-irza commented
При редактировании рецепта, когда идет POST запрос с jQuery почему то Recipe равняется null

2020-11-19 20:07 UTC, alex-geraschenko requested changes

2020-11-19 20:07 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/EditRecipe.cshtml.cs
> +            ModelState.Remove("Name"); //AIrza I do not know why Name is here, I do not have it in my AddIngredientViewModel model
Поле `Name` попадает сюда из основной формы на странице, т.к. все формы обрабатываются внутри одной Razor Page. Выглядит как костыль, но пока более правильного решения (и простого) я не вижу

2020-11-19 20:07 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/EditRecipe.cshtml.cs
> +                Recipe.Ingredients.Add(model.RecipeIngredient); //AIrza Here always null
Здесь именно `Recipe` пустой, т.к. при отправке формы для ингредиента значения рецепта не отправляются, а значит на сервере нечему заполнятся. В этом случае лучше вычитывать рецепт из базы по `model.RecipeIngredient.RecipeId`. Кроме этого необходимо обеспечить так же и сохранение связки рецепта и ингредиентов (`RecipeIngredient`)

2020-11-19 20:07 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/Startup.cs
> +                s.RegisterValidatorsFromAssemblyContaining<RecipeValidator>();
Повторять `RegisterValidatorsFromAssemblyContaining` для каждого валидатора не нужно. Этот метод зарегистрирует все валидаторы, которые найдет в сборке, в которой присутствует указаный тип (в Вашем случае `CategoryValidator`)

2020-11-19 20:07 UTC, alex-geraschenko commented on RecipeBook2/RecipeBook2.Web/wwwroot/js/site.js
> +        var form = $(this).parents('.modal').find('form');
А почему Вы не используете `form1`, ведь получение элемента по id (`#add-ingredient-form`) дает уникальный результат.

2020-11-19 20:12 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Web/wwwroot/js/site.js
> +        var form = $(this).parents('.modal').find('form');
form1 лишний, так как этот скрипт отрабатыват для 2 кнопок Add Ingredient и Add Direction

2020-11-19 20:20 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Web/Startup.cs
> +                s.RegisterValidatorsFromAssemblyContaining<RecipeValidator>();
Почитал, исправил

2020-11-19 21:58 UTC, alexandr-irza commented on RecipeBook2/RecipeBook2.Web/Pages/Recipes/EditRecipe.cshtml.cs
> +                Recipe.Ingredients.Add(model.RecipeIngredient); //AIrza Here always null
Переделал немного логику, вроде бы все получилось

2020-11-23 19:29 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-11-24 11:12 UTC, merged